spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://christianmedina_db_user:Iplacex2026@cluster-spring.taqvqn4.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=discografica-db