spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://eva2_spring:Iplacex2026@cluster-spring.wffzmee.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=discografica-db